# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addstaff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addstaff(object):
    def setupUi(self, addstaff):
        addstaff.setObjectName("addstaff")
        addstaff.resize(341, 164)
        self.centralwidget = QtWidgets.QWidget(addstaff)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_submit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_submit.setGeometry(QtCore.QRect(10, 100, 321, 41))
        self.btn_submit.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 75 14pt \"Bahnschrift\"; \n"
"color: rgb(255, 255, 255);")
        self.btn_submit.setObjectName("btn_submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.label.setStyleSheet("font: 75 14pt \"Bahnschrift\"; color: rgb(0, 85, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.label_2.setStyleSheet("font: 75 14pt \"Bahnschrift\"; color: rgb(0, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.staff_code = QtWidgets.QLineEdit(self.centralwidget)
        self.staff_code.setGeometry(QtCore.QRect(150, 20, 181, 31))
        self.staff_code.setObjectName("staff_code")
        self.staff_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.staff_pass.setGeometry(QtCore.QRect(150, 60, 181, 31))
        self.staff_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.staff_pass.setObjectName("staff_pass")
        addstaff.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addstaff)
        self.statusbar.setObjectName("statusbar")
        addstaff.setStatusBar(self.statusbar)

        self.retranslateUi(addstaff)
        QtCore.QMetaObject.connectSlotsByName(addstaff)

    def retranslateUi(self, addstaff):
        _translate = QtCore.QCoreApplication.translate
        addstaff.setWindowTitle(_translate("addstaff", "MainWindow"))
        self.btn_submit.setText(_translate("addstaff", "Thêm Nhân Viên"))
        self.label.setText(_translate("addstaff", "Mã Nhân Viên"))
        self.label_2.setText(_translate("addstaff", "Mật Khẩu"))
