# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timekeeping.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimekeepingSystem(object):
    def setupUi(self, TimekeepingSystem):
        TimekeepingSystem.setObjectName("TimekeepingSystem")
        TimekeepingSystem.resize(1042, 653)
        TimekeepingSystem.setStyleSheet("font: italic 12pt \"Bahnschrift\";\n"
"color: rgb(0, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(TimekeepingSystem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1021, 611))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMouseTracking(False)
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 181, 261))
        self.label_3.setStyleSheet(" border: 1px solid rgb(85, 170, 127);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.staff_code = QtWidgets.QLabel(self.frame)
        self.staff_code.setEnabled(True)
        self.staff_code.setGeometry(QtCore.QRect(200, 90, 181, 41))
        self.staff_code.setStyleSheet("font: 100 13pt \"Bahnschrift\";\n"
"background-color: rgb(200, 200, 200);\n"
"color:  rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 255);\n"
"selection-background-color: rgb(170, 255, 255);\n"
" border: 1px solid rgb(85, 170, 127);\n"
"")
        self.staff_code.setAlignment(QtCore.Qt.AlignCenter)
        self.staff_code.setObjectName("staff_code")
        self.btn_confirm = QtWidgets.QPushButton(self.frame)
        self.btn_confirm.setGeometry(QtCore.QRect(10, 360, 371, 141))
        self.btn_confirm.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Bahnschrift\";")
        self.btn_confirm.setObjectName("btn_confirm")
        self.label_image = QtWidgets.QLabel(self.frame)
        self.label_image.setGeometry(QtCore.QRect(20, 100, 161, 241))
        self.label_image.setStyleSheet(" border: 1px solid rgb(85, 170, 127);")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.btn_clear = QtWidgets.QPushButton(self.frame)
        self.btn_clear.setGeometry(QtCore.QRect(200, 280, 181, 71))
        self.btn_clear.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Bahnschrift\";")
        self.btn_clear.setObjectName("btn_clear")
        self.in_out = QtWidgets.QLabel(self.frame)
        self.in_out.setGeometry(QtCore.QRect(10, 510, 1001, 91))
        self.in_out.setStyleSheet("color: rgb(255, 170, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 25pt \"Bahnschrift\";\n"
" border: 1px solid rgb(85, 170, 127);")
        self.in_out.setText("")
        self.in_out.setAlignment(QtCore.Qt.AlignCenter)
        self.in_out.setObjectName("in_out")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 291, 21))
        self.label_2.setStyleSheet("font: 75 14pt \"Bahnschrift\";\n"
"color: rgb(0, 85, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.show_video = QtWidgets.QLabel(self.frame)
        self.show_video.setGeometry(QtCore.QRect(390, 10, 621, 491))
        self.show_video.setStyleSheet(" border: 1px solid rgb(85, 170, 127);")
        self.show_video.setText("")
        self.show_video.setObjectName("show_video")
        self.staff_name = QtWidgets.QLabel(self.frame)
        self.staff_name.setGeometry(QtCore.QRect(200, 140, 181, 41))
        self.staff_name.setStyleSheet("font: 100 10pt \"Bahnschrift\";\n"
"background-color: rgb(200, 200, 200);\n"
"color: rgb(0, 170, 0);\n"
"border-color: rgb(0, 170, 255);\n"
"selection-background-color: rgb(170, 255, 255);\n"
" border: 1px solid rgb(85, 170, 127);\n"
"")
        self.staff_name.setAlignment(QtCore.Qt.AlignCenter)
        self.staff_name.setObjectName("staff_name")
        self.note_reason = QtWidgets.QPlainTextEdit(self.frame)
        self.note_reason.setGeometry(QtCore.QRect(200, 190, 181, 81))
        self.note_reason.setStyleSheet(" border: 1px solid rgb(85, 170, 127);")
        self.note_reason.setReadOnly(False)
        self.note_reason.setPlainText("")
        self.note_reason.setObjectName("note_reason")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(610, 570, 401, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 51))
        self.label.setStyleSheet("font: 2 italic 22pt \"Bahnschrift\";\n"
"color: rgb(0, 85, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame)
        TimekeepingSystem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TimekeepingSystem)
        self.statusbar.setObjectName("statusbar")
        TimekeepingSystem.setStatusBar(self.statusbar)

        self.retranslateUi(TimekeepingSystem)
        QtCore.QMetaObject.connectSlotsByName(TimekeepingSystem)

    def retranslateUi(self, TimekeepingSystem):
        _translate = QtCore.QCoreApplication.translate
        TimekeepingSystem.setWindowTitle(_translate("TimekeepingSystem", "MainWindow"))
        self.staff_code.setText(_translate("TimekeepingSystem", "  Mã nhân viên"))
        self.btn_confirm.setText(_translate("TimekeepingSystem", "Xác Nhận"))
        self.label_image.setText(_translate("TimekeepingSystem", "Image"))
        self.btn_clear.setText(_translate("TimekeepingSystem", "Làm sạch"))
        self.label_2.setText(_translate("TimekeepingSystem", "Hệ thống Chấm Công"))
        self.staff_name.setText(_translate("TimekeepingSystem", "  Tên nhân viên"))
        self.note_reason.setToolTip(_translate("TimekeepingSystem", "<html><head/><body><p>Lý do bạn đến muộn? hoặc Lý do bạn về sớm</p></body></html>"))
        self.label_5.setText(_translate("TimekeepingSystem", "Copyright 2022 © RYNAN Techonologies Vietnam"))
        self.label.setText(_translate("TimekeepingSystem", "RYNAN Technologies Vietnam"))
